### ISSUE TITLE
error 1.20.6

### ISSUE THREAD

**Issue by danyadanya2005** [imDaniX/WGExtender#1]
https://pastebin.com/xYxcMAiF

**Comment by imDaniX** [comment]
See https://github.com/imDaniX/WGExtender/releases/tag/v3.1.1
Resolved with https://github.com/imDaniX/WGExtender/commit/20c55a08c32855c20b6aa947ae87bb5cf87462e2

I've only test auto-flags feature, so no guarantee everything works as intended. In such case, create a new issue.

**Comment by StKillReal** [comment]
@imDaniX Спасибо за 1.20.6, дружище
