### ISSUE TITLE
Отсутствие проверок на флаги (`-`) при привате

### ISSUE THREAD

**Issue by WhyXLeak** [imDaniX/WGExtender#7]
Данный плагин создаёт следующий баг:
1. Создаём регион с тире "-gg" (/rg claim -gg)
2. Пытаемся удалить /rg rem -gg - пишет "Too few arguments", с кавычками тоже не работает

Как должно быть (Если пробовать без WGExtender)
1. Пытаемся создать регион с тире "-gg" пишет "Too few arguments" и регион не создаётся

Очень надеюсь, что данный баг исправят, т.к. плагин действительно очень важный для некоторых серверов и аналогов я ему не вижу!

**Comment by imDaniX** [comment]
Добавил в последнем коммите. Скачать билд можно во вкладке [Actions](https://github.com/imDaniX/WGExtender/actions/runs/10874711938).
