### ISSUE TITLE
перевод в классе. (исправь пж)

### ISSUE THREAD

**Issue by GG-MD** [imDaniX/WGExtender#8]
Привет, перевели весь WG, в твоём плагине кое что переписывает из WG. 
О чём речь:
![image](https://github.com/user-attachments/assets/fa8a0267-3919-4b0b-8a57-af39125a927a)

Где это в коде?
Класс: wgextender/features/regionprotect/ownormembased/PvPHandlingListener
Метод: void onDamageEntity(com/sk89q/worldguard/bukkit/event/entity/DamageEntityEvent)
Номер строки: 96

Исправь пожалуйста на: `изменять это`

**Comment by imDaniX** [comment]
Duplicate of #5

**Comment by imDaniX** [comment]
В ближайшее время сделаю. "not planned" указал случайно

**Comment by GG-MD** [comment]
> В ближайшее время сделаю. "not planned" указал случайно

Ближайшее это какое ??

**Comment by imDaniX** [comment]
До конца недели билд с настраиваемыми сообщениями будет, в том числе эти параметры.

**Comment by GG-MD** [comment]
> До конца недели билд с настраиваемыми сообщениями будет, в том числе эти параметры.

??

**Comment by imDaniX** [comment]
В больницу попал, так что были определённые сложности. Ближайшие пару дней будет.

**Comment by GG-MD** [comment]
> В больницу попал, так что были определённые сложности. Ближайшие пару дней будет.

выздоравливай, спасибо)

**Comment by GG-MD** [comment]
> В больницу попал, так что были определённые сложности. Ближайшие пару дней будет.

Скоро ?
